name: Festone
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6213919341098517
title: Festone - 25 Jahre CSN
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffefd'
    - '#c8c0bd'
    - '#302c2d'
    - '#8a2b34'
    - '#978f88'
  brandStrength: 0.6674035445321351
  lightness: 0.3709149328060448
  saturation: 0.8362911166623235
  rhythmicContrast: 0.6023062714375556
purpose: []
